### ISSUE TITLE
[Relation Viewer] Let’s find new tree viewer library

### ISSUE THREAD

**Issue by chshin59** [SSDC-AndroMETA/ONE-vscode#10]
## What?
- **tree view**
![tree-view](https://user-images.githubusercontent.com/97646064/190435797-fa244322-b1ea-457b-b81c-954f5d31ae42.png)

`CircleGraph` uses a library called `netron` to implement circle file viewer.

Since our first reference was `CircleGraph`, we naturally tried to implement the tree viewer with the `dagre.js` used by `netron`.
However, unlike `CircleGraph`, `Relation Viewer` does not necessarily have to use `dagre.js` because the purpose of the two is different. (and also `dagre.js` is [deprecated](https://github.com/dagrejs/dagre-d3#important))

So, we will be able to use any library as long as the following requirements are met.

### Requirements

1. We have not enough time. The **easier** it is to learn, the better.
2. It should be able to visualize the **tree view** effectively.
3. **License** check
[https://github.com/Samsung/ONE-vscode/wiki/License](https://github.com/Samsung/ONE-vscode/wiki/License)

### Candidates

1. [d3.js](https://github.com/d3/d3-hierarchy)
*famous (It's under active development and has a vibrant community.)*
2. [treant-js](https://fperucic.github.io/treant-js/)
*[easy](https://github.com/fperucic/treant-js/tree/master/examples/basic-example)*
3. or else?

Candidate1 seems to me to be a safe choice. 🤔

**Comment by smj53** [comment]
It would be nice to try the difficult one(`1. d3.js`)... But I'm still worried about time, so it will be OK to use `2. trean-js`.
I found new library [cola.js](https://ialab.it.monash.edu/webcola/doc/index.html) too. It's interactive feature looks cool. 😄

**Comment by chshin59** [comment]
![image](https://user-images.githubusercontent.com/97646064/190845317-75c97815-3438-4c4b-8c03-d022ff75daa1.png)
I think `d3.js` is pretty good. I used `d3.js` to open this WebviewPanel.
(The data used is dummy data. It will be changed to relation data later.)

Reference:  https://bl.ocks.org/d3noob/b024fcce8b4b9264011a1c3e7c7d70dc

**Comment by chshin59** [comment]
I will close this issue because we decided to use the `d3.js` library.
